### ISSUE TITLE
Error with ESPHome version 2025.05

### ISSUE THREAD

**Issue by VavpyDreko** [tobias-93/esphome-ecodan-heatpump#18]
Hi, here is the error:

INFO ESPHome 2025.5.0
INFO Reading configuration /config/esphome/heat-pump.yaml...
ERROR Unable to load component ecodan.switch:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 185, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/external_components/50e6a440/components/ecodan/switch.py", line 16, in <module>
    cv.Optional("power_state"): switch.switch_schema(
                                ^^^^^^^^^^^^^^^^^^^^^
TypeError: switch_schema() missing 1 required positional argument: 'class_'
Failed config

switch.ecodan: [source /data/packages/50e6a440/heatpump.yaml:117]
  
  Platform not found: 'switch.ecodan'.
  platform: ecodan
  power_state: 
    name: Power state
  force_dhw: 
    name: Force DHW

Thanks,
Tomaz

**Comment by tobias-93** [comment]
Hi, thanks for reporting this issue! Always fun when ESPHome changes some plaform implementation and doesn't even list it in the breaking changes... Anyway, the issue is resolved in the latest main codebase, you should be able to compile with 2025.05!

**Comment by VavpyDreko** [comment]
Thank you for the update, but I'm still getting same error. Am I doing something wrong?

Thanks,
Tomaz

**Comment by tobias-93** [comment]
It could take a while before the repo is updated by your local ESPHome, normally ESPHome only updates once per day.

**Comment by VavpyDreko** [comment]
Ups, I did not know that. Thanks for clarification.
And again, thanks for your great work! Much appreciated. 

Thanks,
Tomaz
